version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=secstor
      - MYSQL_ROOT_PASSWORD=secstor